#spring:
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/blog_api
#    username: root
#    password: root
#    jpa:
#      hibernate.ddl-auto: update
#      generate-ddl: true
#      show-sql: true
#server:
#  port: 9292